on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages
    strategy:
      matrix:
        node-version: [18.10.0]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install --legacy-peer-deps
    - name: Deploy to GH Pages
      run: |
        git config --global user.email "jimmyjcl753@gmail.com"
        git config --global user.name "Jimmy Liu"
        git remote set-url origin https://${{ secrets.GH_PAGES_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
        npm run deploy